image: node:14.18.0

variables:
  GIT_SSL_NO_VERIFY: '1'
  DOCKER_DRIVER: 'overlay2'
  DOCKER_TLS_CERTDIR: ''
  TZ: 'Asia/Shanghai'

stages:
  - test

Lint Test:
  stage: test
  tags:
    - test
  only:
    - main
    - pushes
    - merge_requests
  script:
    - yarn global add pnpm
    - pnpm install
    - pnpm lint:check
