// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppRouterView: typeof import('./components/AppRouterView.vue')['default']
    DemoGlobalComponent: typeof import('./components/DemoGlobalComponent.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LayoutPanel: typeof import('./components/LayoutPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('@jjlc/vant-plus/es')['Button']
    VanCell: typeof import('@jjlc/vant-plus/es')['Cell']
    VanCol: typeof import('@jjlc/vant-plus/es')['Col']
    VanConfigProvider: typeof import('@jjlc/vant-plus/es')['ConfigProvider']
    VanDatePicker: typeof import('@jjlc/vant-plus/es')['DatePicker']
    VanField: typeof import('@jjlc/vant-plus/es')['Field']
    VanForm: typeof import('@jjlc/vant-plus/es')['Form']
    VanList: typeof import('@jjlc/vant-plus/es')['List']
    VanPopup: typeof import('@jjlc/vant-plus/es')['Popup']
    VanPullRefresh: typeof import('@jjlc/vant-plus/es')['PullRefresh']
    VanRate: typeof import('@jjlc/vant-plus/es')['Rate']
    VanRow: typeof import('@jjlc/vant-plus/es')['Row']
    VanSlider: typeof import('@jjlc/vant-plus/es')['Slider']
    VanSwipe: typeof import('@jjlc/vant-plus/es')['Swipe']
    VanSwipeItem: typeof import('@jjlc/vant-plus/es')['SwipeItem']
    VanSwitch: typeof import('@jjlc/vant-plus/es')['Switch']
    VanTab: typeof import('@jjlc/vant-plus/es')['Tab']
    VanTabs: typeof import('@jjlc/vant-plus/es')['Tabs']
  }
}
